Multi_shop_django/urls.py
from itertools import product

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('account/', include('account.urls')),
                  path('product/', include('shop.urls')),
                  path('cart/', include('cart.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns = [
    path('detail', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_list'),
    path('detail/<str:id>', views.OrderDetailView.as_view(), name='cart_detail'),
    path('order/<int:id>', views.OrderAddView.as_view(), name='cart_add'),
    path('apply/<int:pk>', views.ApplyDiscountView.as_view(), name='apply'),
]

cart/models.py
from django.db import models

from account.models import User
from shop.models import Detail


# products that the user must register
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user


# Products registered by the user
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')  # profition
    product = models.ForeignKey(Detail, on_delete=models.CASCADE, related_name='items')
    size = models.CharField(max_length=11)
    color = models.CharField(max_length=11)
    quantity = models.SmallIntegerField()
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.order


class DiscountCode(models.Model):
    name = models.CharField(max_length=20)
    discount = models.PositiveIntegerField(default=0, unique=True)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

cart/views.py
from cart.cart_save import Cart
from cart.models import Order, DiscountCode, OrderItem
from shop.models import Detail
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib import messages


class CartDetailView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'cart/cart.html', {'cart': cart})


class CartAddView(View):
    def post(self, request, pk):
        detail = get_object_or_404(Detail, id=pk)
        size = request.POST.get('size')
        color = request.POST.get('color')
        quantity = request.POST.get('quantity')
        if not size or not color or not quantity:
            messages.error(request, 'لطفاً همه گزینه‌ها را انتخاب کنید.')
            return redirect('shop:detail', pk=pk)
        cart = Cart(request)
        cart.add(detail, quantity, size, color)
        return redirect('cart:cart_detail')


class OrderDetailView(View):
    def get(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        return render(request, 'cart/order_detail.html', {'order': order})


class OrderAddView(View):
    def get(self, request):
        cart = Cart(request)
        order = Order.object.create(user=request.user, total_price=cart.total)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'], color=item['color'],
                                     size=item['size'], quantity=item['quantity'])
        return redirect('cart:order_detail', order.id)


class ApplyDiscountView(View):
    def post(self, request, pk):
        code = request.POST.get('code')
        order = get_object_or_404(Order, id=pk)
        discount_code = get_object_or_404(DiscountCode, name=code)
        if discount_code.quantity == 0:
            return redirect('cart:cart_detail', order.id)
        order.total_price -= discount_code.quantity * order.price
        order.save()
        discount_code.quantity -= 1
        discount_code.save()
        return redirect('cart:cart_detail', order.id)

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Color</th>
                        <th>Size</th>

                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in cart %}
                        <tr>
                            <td class="align-middle"><img src="{{ item.detail.image.url }}" alt="" style="width: 50px;">
                                Product Name
                            </td>
                            <td class="align-middle">{{ item.detail.title }}</td>
                            <td class="align-middle">${{ item.price }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size }}</td>
                            <td class="align-middle">
                                {{ item.total }}
                            <td>
                            <td>
                                <button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" method="post" action="{% url 'cart:apply' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="code" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ cart.total }}</h5>
                        </div>
                        <a href="{% url 'address' %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">>Proceed
                            To Checkout </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->



{% endblock %}

cart/templates/cart/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Color</th>
                        <th>Size</th>

                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in cart %}
                        <tr>
                            <td class="align-middle"><img src="{{ item.detail.image.url }}" alt="" style="width: 50px;">
                                Product Name
                            </td>
                            <td class="align-middle">{{ item.detail.title }}</td>
                            <td class="align-middle">${{ item.price }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size }}</td>
                            <td class="align-middle">
                                {{ item.total }}
                            <td>
                            <td>
                                <button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" method="post" action="{% url 'cart:apply' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="code" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ cart.total }}</h5>
                        </div>
                        <a href="#" class="btn btn-block btn-success font-weight-bold my-3 py-3">PUT</a>
                        <a href="{% url 'address' %}" class="btn btn-block btn-success font-weight-bold my-3 py-3">Add Address</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->



{% endblock %}