Multi_shop_django/urls.py
from itertools import product

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('account/', include('account.urls')),
                  path('product/', include('shop.urls')),
                  path('cart/', include('cart.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns = [
    path('detail', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_list'),
    path('detail/<str:id>', views.OrderDetailView.as_view(), name='cart_detail'),
    path('order/<int:id>', views.OrderAddView.as_view(), name='cart_add'),
    path('apply/<int:pk>', views.ApplyDiscountView.as_view(), name='apply'),
]

home/urls.py
from django.urls import path
from .views import HomePageView
from home.views import CategoryListView

app_name = 'home'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('category/',CategoryListView.as_view(), name='category-list'),
]

shop/urls.py
from django.urls import path
from . import views
from .views import ShopDetailView

app_name = 'shop'
urlpatterns = [
    path('', ShopDetailView.as_view(), name='shop'),
    path('shop/detail', ShopDetailView.as_view(), name='shap_detail'),
    path('new_product', views.new_product_view, name='new_product'),
]

shop/models.py
from django.db import models

from home.models import Category


class Size(models.Model):
    title = models.CharField(null=True, blank=True, max_length=10, verbose_name='سایز')

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(null=True, blank=True, max_length=15, verbose_name='رنگ')

    def __str__(self):
        return self.title


class Detail(models.Model):
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=100, verbose_name='نام کالا')
    description = models.TextField(verbose_name='توضیحات')
    image = models.ImageField(upload_to='detail_img/', verbose_name='عکس')
    price = models.FloatField(verbose_name='قیمت')
    status = models.BooleanField(default=False, verbose_name='وضعیت')
    size = models.ManyToManyField(Size, blank=True, related_name='size', verbose_name='سایز')
    color = models.ManyToManyField(Color, blank=True, related_name='color', verbose_name='رنگ')
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True, verbose_name='زمان')

    def __str__(self):
        return self.title


class Information(models.Model):
    product = models.ForeignKey(Detail, null=True, on_delete=models.CASCADE, related_name='information')
    text = models.TextField()

    def __str__(self):
        return self.text[:20]

shop/views.py
from django.template.context_processors import request
from django.template import Template
from django.views.generic import DetailView, TemplateView, ListView
from django.shortcuts import render
from shop.models import Detail


class ShopDetailView(TemplateView):
    template_name = 'shop/shop.html'
    model = Detail

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contexts'] = Detail.objects.all()
        return context


class ProductListView(ListView):
    template_name = 'shop/shop.html'
    queryset = Detail.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        colors = request.GET.getlist('color')
        sizes = request.GET.getlist('size')
        min_price = request.GET.getlist('min_price')
        max_price = request.GET.getlist('max_price')
        queryset = Detail.objects.all()

        if colors:
            queryset = queryset.filter(color__title__in=colors).distinct()
        if sizes:
            queryset = queryset.filter(size__title__in=sizes).distinct()
        if min_price and max_price:
            queryset = queryset.filter(price__lte=max_price, price__gte=min_price)
        context = super(ProductListView, self).get_context_data()
        context['objects_list'] = queryset



def new_product_view(request):
    new_product = Detail.objects.order_by('created_at')[:10]
    return render(request, 'home/index.html', {'product': new_product})

shop/templates/shop/shop.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">{% url 'home:home' %}</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Shop List</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span>
                </h5>
                <div class="bg-light p-4 mb-30">
                    <form>
                        <div class=" form-control d-flex align-items-center justify-content-between mb-3">
                            <input type="number" name="min_price" class="form-control" checked id="price-all">
                            <label class="form-label" for="price-all">Min</label>

                        </div>
                        <div class="form-control d-flex align-items-center justify-content-between mb-3">
                            <input type="number" name="max_price" class="form-control" id="price-1">
                            <label class="from-label" for="price-1">Max</label>

                        </div>

                </div>
                <!-- Price End -->

                <!-- Color Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by color</span>
                </h5>
                <div class="bg-light p-4 mb-30">

                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="warning" name="colors" class="custom-control-input" checked
                               id="color-all">
                        <label class="custom-control-label" for="price-all">warning</label>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="red" name="colors" class="custom-control-input" id="color-1">
                        <label class="custom-control-label" for="color-1">Red</label>

                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="danjer" name="colors" class="custom-control-input" id="color-2">
                        <label class="custom-control-label" for="color-2">Danger</label>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="darck" name="colors" class="custom-control-input" id="color-3">
                        <label class="custom-control-label" for="color-3">Dark</label>
                    </div>

                </div>
                <!-- Color End -->

                <!-- Size Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span>
                </h5>
                <div class="bg-light p-4 mb-30">
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="XXL" class="custom-control-input" checked id="size-all">
                        <label class="custom-control-label" for="size-all">XXL</label>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="XL" class="custom-control-input" id="size-1">
                        <label class="custom-control-label" for="size-1">XL</label>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="M" class="custom-control-input" id="size-2">
                        <label class="custom-control-label" for="size-2">M</label>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" value="L" class="custom-control-input" id="size-3">
                        <label class="custom-control-label" for="size-3">L</label>
                    </div>

                </div>
                </form>
                <button type="submit" class="btn btn-warning">Submit</button>
                <!-- Size End -->
            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div>
                                <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                                <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                            </div>
                            <div class="ml-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Sorting
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">Latest</a>
                                        <a class="dropdown-item" href="#">Popularity</a>
                                        <a class="dropdown-item" href="#">Best Rating</a>
                                    </div>
                                </div>
                                <div class="btn-group ml-2">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Showing
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">10</a>
                                        <a class="dropdown-item" href="#">20</a>
                                        <a class="dropdown-item" href="#">30</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                        <div class="product-item bg-light mb-4">
                            {% for item in contexts %}
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="{{ item.image.url }}" alt="">
                                    <div class="product-action">
                                        <a class="btn btn-outline-dark btn-square" href=""><i
                                                class="fa fa-shopping-cart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i
                                                class="fa fa-sync-alt"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" href="">{{ item.title }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>{{ item.price }}</h5>
                                    <h6 class="text-muted ml-2">
                                        <del>$123.00</del>
                                    </h6>
                                </div>
                            {% endfor %}

                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <nav>
                            {% if page_obj.paginator.has_other_pages %}
                                <ul class="pagination justify-content-center">

                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">Previous</span>
                                        </li>
                                    {% endif %}

                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <span class="page-link">{{ i }}</span>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <span class="page-link">Next</span>
                                        </li>
                                    {% endif %}

                                </ul>
                            {% endif %}
                        </nav>

                        </nav>
                    </div>
                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->
{% endblock %}